#!/usr/bin/env ruby

# aws_s3_write
#
# Write a file to AWS S3 bucket.

require 'aws-sdk'

file = ARGV[0]

puts "Writing file \'#{file}\'..."

s3 = AWS::S3.new(
  :access_key_id => ENV['AWS_ID'],
  :secret_access_key => ENV['AWS_SECRET'])
bucket = s3.buckets[ENV['AWS_S3_BUCKET']]

object = bucket.objects[File.basename(file)]
object.write(:file => file)

puts "Done writing #{File.basename(file)} to bucket named \'#{ENV['AWS_S3_BUCKET']}\'"
