#!/bin/bash

set -e

nginx_version="$1"
pcre_version="$2"

if [ -z "$nginx_version" -o -z "$pcre_version" ]; then
  echo "usage: $0 NGINX_VERSION PCRE_VERSION"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir=$(mktemp -d -t nginx.XXXXXX)
pushd $tempdir

curl http://nginx.org/download/nginx-${nginx_version}.tar.gz -o nginx.tgz
tar xzf nginx.tgz

curl -L http://downloads.sourceforge.net/pcre/pcre-${pcre_version}.tar.gz -o pcre.tgz
tar xzf pcre.tgz

# build and package nginx for heroku
vulcan build -v -n nginx -o $tempdir/nginx-${nginx_version}.tgz -c "cd nginx-${nginx_version} && ./configure --prefix=/app/vendor/nginx --with-pcre=../pcre-${pcre_version} --with-http_stub_status_module --with-http_gzip_static_module --with-http_realip_module --with-http_ssl_module && make install"

# upload nginx to s3
$basedir/aws_s3_write $tempdir/nginx-${nginx_version}.tgz
